#!/usr/bin/env bats
# The generated Claude guard: a PreToolUse hook that blocks an edit to a
# generated file and names the source to edit instead.

load test_helper

setup() {
    setup_test_project
    run_agentsync init --tools claude --yes >/dev/null 2>&1
    GUARD=".claude/hooks/agentsync-guard.sh"
}

teardown() {
    teardown_test_project
}

# Feed the hook a PreToolUse payload for <path>, as Claude Code would.
guard_for() {
    printf '{"hook_event_name":"PreToolUse","tool_name":"Edit","tool_input":{"file_path":"%s"}}' "$1" \
        | CLAUDE_PROJECT_DIR="$TEST_PROJECT" sh "$GUARD"
}

@test "guard: sync installs it as an executable hook" {
    [ -f "$GUARD" ]
    [ -x "$GUARD" ]
}

@test "guard: settings point PreToolUse at it" {
    grep -q "agentsync-guard.sh" .claude/settings.json
    grep -q "PreToolUse" .claude/settings.json
}

@test "guard: it is tracked in the manifest like any other output" {
    grep -q "^.claude/hooks/agentsync-guard.sh"$'\t' .ai/.sync-manifest
}

@test "guard: blocks an edit to a generated rule with exit 2" {
    run guard_for "$TEST_PROJECT/.claude/rules/core.md"
    [ "$status" -eq 2 ]
    [[ "$output" == *".ai/src/"* ]]
    [[ "$output" == *"agentsync sync"* ]]
}

@test "guard: blocks an edit to the generated agents file" {
    run guard_for "$TEST_PROJECT/CLAUDE.md"
    [ "$status" -eq 2 ]
    [[ "$output" == *"generated by AgentSync"* ]]
}

@test "guard: names adopt so an edit already made can be kept" {
    run guard_for "$TEST_PROJECT/CLAUDE.md"
    [[ "$output" == *"agentsync adopt CLAUDE.md"* ]]
}

@test "guard: accepts a repo-relative path too" {
    run guard_for "CLAUDE.md"
    [ "$status" -eq 2 ]
}

@test "guard: allows a source file under .ai/src/" {
    run guard_for "$TEST_PROJECT/.ai/src/rules/core.md"
    [ "$status" -eq 0 ]
    [ -z "$output" ]
}

@test "guard: allows ordinary project files" {
    run guard_for "$TEST_PROJECT/lib/main.dart"
    [ "$status" -eq 0 ]
}

@test "guard: allows a file outside the project" {
    run guard_for "/etc/hosts"
    [ "$status" -eq 0 ]
}

@test "guard: allows everything when there is no manifest" {
    rm .ai/.sync-manifest
    run guard_for "$TEST_PROJECT/CLAUDE.md"
    [ "$status" -eq 0 ]
}

@test "guard: allows a payload with no file_path" {
    printf '{"tool_name":"Bash","tool_input":{"command":"ls"}}' > payload.json
    run env CLAUDE_PROJECT_DIR="$TEST_PROJECT" sh -c "sh '$GUARD' < payload.json"
    [ "$status" -eq 0 ]
}

@test "guard: a project override replaces the shipped script" {
    mkdir -p .ai/src/tools/claude
    printf '#!/bin/sh\nexit 0\n' > .ai/src/tools/claude/guard.sh
    run_agentsync sync --force >/dev/null 2>&1
    run guard_for "$TEST_PROJECT/CLAUDE.md"
    [ "$status" -eq 0 ]
}
